const { Player } = require('../models');

const players = [
  {
    playerName: 'RedGuard',
    playerLevel: 1,
    playerHealth: 10,
    experience: 0,
    CampaignId: 1,
  },
  {
    playerName: 'RedGuard',
    playerLevel: 2,
    playerHealth: 12,
    experience: 0,
    CampaignId: 1,
  }, {
    playerName: 'RedGuard',
    playerLevel: 3,
    playerHealth: 14,
    experience: 0,
    CampaignId: 1,
  }, {
    playerName: 'RedGuard',
    playerLevel: 4,
    playerHealth: 16,
    experience: 0,
    CampaignId: 1,
  }, {
    playerName: 'RedGuard',
    playerLevel: 5,
    playerHealth: 18,
    experience: 0,
    CampaignId: 1,
  }, {
    playerName: 'RedGuard',
    playerLevel: 6,
    playerHealth: 20,
    experience: 0,
    CampaignId: 1,
  }, {
    playerName: 'RedGuard',
    playerLevel: 7,
    playerHealth: 22,
    experience: 0,
    CampaignId: 1,
  }, {
    playerName: 'RedGuard',
    playerLevel: 8,
    playerHealth: 24,
    experience: 0,
    CampaignId: 1,
  }, {
    playerName: 'RedGuard',
    playerLevel: 9,
    playerHealth: 26,
    experience: 0,
    CampaignId: 1,
  },
  {
    playerName: 'Demolitionist',
    playerLevel: 1,
    playerHealth: 8,
    experience: 0,
    CampaignId: 1,
  },
  {
    playerName: 'Demolitionist',
    playerLevel: 2,
    playerHealth: 9,
    experience: 0,
    CampaignId: 1,
  }, {
    playerName: 'Demolitionist',
    playerLevel: 3,
    playerHealth: 11,
    experience: 0,
    CampaignId: 1,
  }, {
    playerName: 'Demolitionist',
    playerLevel: 4,
    playerHealth: 12,
    experience: 0,
    CampaignId: 1,
  }, {
    playerName: 'Demolitionist',
    playerLevel: 5,
    playerHealth: 14,
    experience: 0,
    CampaignId: 1,
  }, {
    playerName: 'Demolitionist',
    playerLevel: 6,
    playerHealth: 15,
    experience: 0,
    CampaignId: 1,
  }, {
    playerName: 'Demolitionist',
    playerLevel: 7,
    playerHealth: 17,
    experience: 0,
    CampaignId: 1,
  }, {
    playerName: 'Demolitionist',
    playerLevel: 8,
    playerHealth: 18,
    experience: 0,
    CampaignId: 1,
  }, {
    playerName: 'Demolitionist',
    playerLevel: 9,
    playerHealth: 20,
    experience: 0,
    CampaignId: 1,
  },
  {
    playerName: 'Hatchet',
    playerLevel: 1,
    playerHealth: 8,
    experience: 0,
    CampaignId: 1,
  },
  {
    playerName: 'Hatchet',
    playerLevel: 2,
    playerHealth: 9,
    experience: 0,
    CampaignId: 1,
  }, {
    playerName: 'Hatchet',
    playerLevel: 3,
    playerHealth: 11,
    experience: 0,
    CampaignId: 1,
  }, {
    playerName: 'Hatchet',
    playerLevel: 4,
    playerHealth: 12,
    experience: 0,
    CampaignId: 1,
  }, {
    playerName: 'Hatchet',
    playerLevel: 5,
    playerHealth: 14,
    experience: 0,
    CampaignId: 1,
  }, {
    playerName: 'Hatchet',
    playerLevel: 6,
    playerHealth: 15,
    experience: 0,
    CampaignId: 1,
  }, {
    playerName: 'Hatchet',
    playerLevel: 7,
    playerHealth: 17,
    experience: 0,
    CampaignId: 1,
  }, {
    playerName: 'Hatchet',
    playerLevel: 8,
    playerHealth: 18,
    experience: 0,
    CampaignId: 1,
  }, {
    playerName: 'Hatchet',
    playerLevel: 9,
    playerHealth: 20,
    experience: 0,
    CampaignId: 1,
  },
  {
    playerName: 'Voidwarden',
    playerLevel: 1,
    playerHealth: 6,
    experience: 0,
    CampaignId: 1,
  },
  {
    playerName: 'Voidwarden',
    playerLevel: 2,
    playerHealth: 7,
    experience: 0,
    CampaignId: 1,
  },
  {
    playerName: 'Voidwarden',
    playerLevel: 3,
    playerHealth: 8,
    experience: 0,
    CampaignId: 1,
  },
  {
    playerName: 'Voidwarden',
    playerLevel: 4,
    playerHealth: 9,
    experience: 0,
    CampaignId: 1,
  },
  {
    playerName: 'Voidwarden',
    playerLevel: 5,
    playerHealth: 10,
    experience: 0,
    CampaignId: 1,
  },
  {
    playerName: 'Voidwarden',
    playerLevel: 6,
    playerHealth: 11,
    experience: 0,
    CampaignId: 1,
  },
  {
    playerName: 'Voidwarden',
    playerLevel: 7,
    playerHealth: 12,
    experience: 0,
    CampaignId: 1,
  },
  {
    playerName: 'Voidwarden',
    playerLevel: 8,
    playerHealth: 13,
    experience: 0,
    CampaignId: 1,
  },
  {
    playerName: 'Voidwarden',
    playerLevel: 9,
    playerHealth: 14,
    experience: 0,
    CampaignId: 1,
  }
];

const seedPlayers = () => Player.bulkCreate(players);

module.exports = seedPlayers;
